const data = {
    categories: [
        {
            title: 'Furniture',
            slug: 'furniture',
            image: './images/products/furniture.png',
        },
        {
            title: 'Home Appliances',
            slug: 'home-appliances',
            image: './images/products/furniture.png',
        },
        {
            title: 'Electronics',
            slug: 'electronics',
            image: './images/products/furniture.png',
        },
        {
            title: 'Services',
            slug: 'services',
            image: './images/products/furniture.png',
        },

    ],
    products: [
        {
            id: 1,
            name: 'sofa set',
            category: 'furniture',
            image: './images/products/brown-sofa-set.jpg',
            price: '2000',
            description: 'Comfy sofa set',
        },
        {
            id: 2,
            name: 'caramboard',
            category: 'furniture',
            image: './images/products/caramboard.jpg',
            price: '2000',
            description: 'Good to play',
        },
        {
            id: 3,
            name: 'clock',
            category: 'home-appliances',
            image: './images/products/clock.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 4,
            name: 'clock',
            category: 'home-appliances',
            image: './images/products/clock2.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 5,
            name: 'table',
            category: 'furniture',
            image: './images/products/counterTable.jpg',
            price: '2000',
            description: 'Counter table for shops',
        },
        {
            id: 6,
            name: 'cup and plate',
            category: 'home-appliances',
            image: './images/products/cupplate.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 7,
            name: 'cups',
            category: 'home-appliances',
            image: './images/products/cups.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 8,
            name: 'daraz',
            category: 'furniture',
            image: './images/products/daraz.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 9,
            name: 'daraz',
            category: 'furniture',
            image: './images/products/Daraz2.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 10,
            name: 'dining table',
            category: 'diningtable',
            image: './images/products/diningtable.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 11,
            name: 'cage',
            category: 'home-appliances',
            image: './images/products/dogcage.jpg',
            price: '2000',
            description: 'Cage for your pet animal',
        },
        {
            id: 12,
            name: 'fridge',
            category: 'home-appliances',
            image: './images/products/Freezer.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 13,
            name: 'fridge',
            category: 'home-appliances',
            image: './images/products/Fridge.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 14,
            name: 'glass cup',
            category: 'home-appliances',
            image: './images/products/glasscup.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 15,
            name: 'glass cup',
            category: 'home-appliances',
            image: './images/products/glasscup2.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 16,
            name: 'glass cup',
            category: 'home-appliances',
            image: './images/products/glasscup3.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 17,
            name: 'glass cup',
            category: 'home-appliances',
            image: './images/products/glasscup4.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 18,
            name: 'glass cup',
            category: 'home-appliances',
            image: './images/products/glasscup5.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 19,
            name: 'heater rod',
            category: 'home-appliances',
            image: './images/products/heaterrod.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 20,
            name: 'television',
            category: 'electronics',
            image: './images/products/Idea-Television.jpg',
            price: '2000',
            description: 'Idea-Television',
        },
        {
            id: 21,
            name: 'small daraz',
            category: 'furniture',
            image: './images/products/kitchenrag.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 22,
            name: 'television',
            category: 'electronics',
            image: './images/products/Kona-Television.jpg',
            price: '2000',
            description: 'Kona',
        },
        {
            id: 23,
            name: 'plate',
            category: 'home-appliances',
            image: './images/products/plate.jpg',
            price: '2000',
            description: 'Plates',
        },
        {
            id: 24,
            name: 'plate',
            category: 'home-appliances',
            image: './images/products/plate2.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 25,
            name: 'sofa',
            category: 'furniture',
            image: './images/products/sofa.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 26,
            name: 'sofa',
            category: 'furniture',
            image: './images/products/sofa2.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 27,
            name: 'sofa',
            category: 'furniture',
            image: './images/products/sofa3.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 28,
            name: '1 piece sofa',
            category: 'furniture',
            image: './images/products/sofa-chair.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 29,
            name: 'sofa set',
            category: 'furniture',
            image: './images/products/sofaset.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 30,
            name: 'sofa set',
            category: 'furniture',
            image: './images/products/sofa-set.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 31,
            name: 'television',
            category: 'electronics',
            image: './images/products/Sony-Television.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 32,
            name: 'study table',
            category: 'home-appliances',
            image: './images/products/Sony-Television.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 33,
            name: 'table and chair',
            category: 'home-appliances',
            image: './images/products/table-chair.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 34,
            name: 'table',
            category: 'home-appliances',
            image: './images/products/table.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 35,
            name: 'television',
            category: 'electronics',
            image: './images/products/Television.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 36,
            name: 'television',
            category: 'electronics',
            image: './images/products/Television2.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 37,
            name: 'television',
            category: 'home-appliances',
            image: './images/products/whiteboard.jpg',
            price: '2000',
            description: '',
        },
        {
            id: 38,
            name: 'glass set',
            category: 'home-appliances',
            image: './images/products/wiskeyglass.jpg',
            price: '2000',
            description: '',
        },
    ]
}

export default data;